using MongoDB.Bson.Serialization.Attributes;

namespace EprRegisterEnrolManagementBe.WorkItems.ReAccreditation.Models;

/// <summary>
/// Payload shape captured at the front-of-funnel ingestion of a
/// re-accreditation work item. Just enough fields to drive the
/// <see cref="IReAccreditationDecisionService"/> recommendation.
///
/// Stored on the work item envelope as a free-form BSON sub-document; this
/// record is the module's interpretation of that document, deserialised on
/// demand when the module needs to reason about the payload.
///
/// Marked <see cref="BsonIgnoreExtraElementsAttribute"/> so envelope-level
/// fields stamped onto the payload by the core <c>WorkItemService</c>
/// (e.g. <c>applicationReference</c>, <c>source</c>, <c>siteAddressLine1</c>)
/// do not cause deserialisation to fail when the module re-reads its
/// own slice of the payload.
/// </summary>
[BsonIgnoreExtraElements]
internal sealed record ReAccreditationPayload
{
    public string? OrganisationName { get; init; }
    public string? RegistrationNumber { get; init; }

    /// <summary>
    /// Human-facing application reference (RA-219, format RA-#########),
    /// stamped onto the payload by the core WorkItemService at submission.
    /// Surfaced as the ((reference)) GOV.UK Notify placeholder in lifecycle
    /// emails (RA-248) so operators see the case reference rather than the
    /// internal work-item Guid. Null only for legacy items predating RA-219.
    /// </summary>
    public string? ApplicationReference { get; init; }

    public string? Material { get; init; }
    public int? PreviousAccreditationYear { get; init; }
    public int? ComplianceIssuesReported { get; init; }

    /// <summary>
    /// ReEx organisation identifier for the submitting operator. Used by the
    /// prior-year endpoint to look up accreditation data from ReEx. Populated
    /// by the operator backend at submission time; absent for work items created
    /// through the case management form.
    /// </summary>
    public string? OperatorOrganisationId { get; init; }

    /// <summary>
    /// ReEx registration identifier for the submitting operator. Used together
    /// with <see cref="OperatorOrganisationId"/> for prior-year lookups.
    /// </summary>
    public string? OperatorRegistrationId { get; init; }

    /// <summary>
    /// Operator email address used as the GOV.UK Notify recipient for
    /// the lifecycle email templates wired up by
    /// <c>ReAccreditationNotificationHook</c> (RA-123). Optional —
    /// notifications are skipped (and recorded as such in the audit
    /// log) when missing.
    /// </summary>
    public string? OperatorEmail { get; init; }

    /// <summary>
    /// Postcode of the regulated site. Used by <c>ReAccreditationNationRoutingHook</c>
    /// (RA-125) to derive the <see cref="Nation"/> field via
    /// <see cref="INationResolver"/>. Optional — when absent the nation
    /// defaults to <see cref="Nation.England"/>.
    /// </summary>
    public string? SiteAddressPostcode { get; init; }

    /// <summary>
    /// The UK nation to which this application is routed, derived from
    /// <see cref="SiteAddressPostcode"/> by <c>ReAccreditationNationRoutingHook</c>
    /// (RA-125). Written by the server at submission time; callers should
    /// not include it in the submission payload.
    /// </summary>
    public Nation? Nation { get; init; }

    /// <summary>
    /// Issued accreditation identifier (RA-132). Generated by the
    /// approval service when a decision-maker approves the application.
    /// </summary>
    public string? AccreditationId { get; init; }

    /// <summary>
    /// Date the issued accreditation takes effect (RA-132). Stamped by
    /// the approval service at the moment of approval.
    /// </summary>
    public DateOnly? AccreditationStartDate { get; init; }

    /// <summary>
    /// Four-digit accreditation year stamped at approval time
    /// (RA-133). Sourced from the <c>Accreditation:CurrentYear</c>
    /// configuration setting and used to derive both the year segment
    /// of <see cref="AccreditationId"/> and the
    /// <see cref="AccreditationStartDate"/>.
    /// </summary>
    public int? AccreditationYear { get; init; }

    /// <summary>
    /// RA-132 SLA clock state. Set by the approval service when the
    /// clock is stopped on approval.
    /// </summary>
    public SlaClock? SlaClock { get; init; }

    /// <summary>
    /// RA-316: the registration charge for this application, in PENCE (minor
    /// units) — £3,276 is 327600. Supplied by the operator backend in the
    /// submission payload and displayed, read-only, on the duly-making page so
    /// the regulator can confirm the charge before recording the payment date.
    ///
    /// Nullable and never written by this service. Absent on every work item
    /// submitted before RA-316, so readers must degrade rather than assume a
    /// value; note that <c>0</c> is a legitimate charge and must not be
    /// conflated with "missing".
    /// </summary>
    public int? ChargeAmountPence { get; init; }

    /// <summary>
    /// RA-316: the operator's payment reference, displayed read-only alongside
    /// <see cref="ChargeAmountPence"/> on the duly-making page.
    ///
    /// Optional and structurally absent on every initial submission: the
    /// operator backend builds its payload before this service has generated the
    /// application reference, so it has nothing to send.
    ///
    /// When absent, the correct value to display is
    /// <see cref="ApplicationReference"/>. That is not a loose approximation —
    /// the operator's own "Payment details" page renders
    /// <c>accreditationReference</c> under the literal label "Payment reference"
    /// alongside the sort code and account number, so it is the reference the
    /// operator actually quotes on the bank transfer. This field is therefore an
    /// OVERRIDE: use it when present, fall back to the application reference
    /// otherwise. It exists as a slot for a genuinely distinct payment reference
    /// in a later story.
    /// </summary>
    public string? PaymentReference { get; init; }

    /// <summary>
    /// RA-316: the payment date the regulator entered when completing duly
    /// making. Stamped by <c>ReAccreditationDulyMakingService</c> at that
    /// moment, and the value <see cref="Core.WorkItemSlaClock.StartedAt"/> is
    /// anchored to — the 12-week SLA runs from when payment was made, not from
    /// when the regulator got round to recording it.
    ///
    /// Null until duly making completes. Written by the server only; callers
    /// must not include it in the submission payload.
    /// </summary>
    public DateOnly? PaymentDate { get; init; }

    /// <summary>
    /// RA-291: the query currently open against this application, stamped by
    /// <c>ReAccreditationQueryService</c> just before the query transition so
    /// the notification hook can include the reason in the operator's email.
    /// See <see cref="Models.CurrentQuery"/> for why this is payload state and
    /// why readers must gate on the <c>queried</c> state.
    /// </summary>
    public CurrentQuery? CurrentQuery { get; init; }
}
